### ISSUE TITLE
Explanation for maximum bound on float?

### ISSUE THREAD

**Issue by modalduality** [hsluv/hsluv#44]
Hi,
I'm working on a Haskell port, didn't see any others. This is a great project, thanks for the work!

I'm wondering about this code:
```
// var min:Float = Float.MAX_VALUE;
var min:Float = 1.7976931348623157e+308;
for (i in 0...2) {
    var length:Float = Geometry.distanceLineFromOrigin(bounds[i]);
    min = Math.min(min, length);
}
```
found at https://github.com/hsluv/hsluv/blob/master/haxe/src/hsluv/Hsluv.hx#L92.

Is the first assignment to `min` meant to be an upper bound on a double-precision floating point value?

Since the number of iterations is at least 1, why not just `Math.min(Geometry.distanceLineFromOrigin[0], Geometry.distanceLineFromOrigin[1])`? Or with keeping the same code structure, `min:Float = POSITIVE_INFINITY;`?

**Comment by boronine** [comment]
Hi @modalduality, thanks for the catch! Actually, the loop should have iterated through all the bounding lines and not just the first two. I changed that, as well as incorporated your suggestion to use POSITIVE_INFINITY here:

https://github.com/hsluv/hsluv/commit/e15d91f432d529cc426ccd1d57a3c3c593e01a05

The change did not affect the return value of this function because maxSafeChromaForL happens to be bounded only by R < 0 and R > 1, which happen to be the first two bounding lines. However, since we do not have a proof for this, it's better to iterate over all bounding lines.

Let me know when and if you complete that Haskell port, we'll add it to the homepage :)
