### ISSUE TITLE
The number precision seems wrong

### ISSUE THREAD

**Issue by SmartHypercube** [hsluv/hsluv#54]
(Sorry about my poor English)

https://github.com/hsluv/hsluv/blob/4b68049494f3eb793589b02abda989dc94fadb59/haxe/src/hsluv/Hsluv.hx#L13

Here, it says 17 digits, but the numbers below is obviously less than 17 digits. Why?

Oddly, in the C version, all the numbers are precise enough:

https://github.com/hsluv/hsluv-c/blob/498de4d9ce7a33933e9252fd3c87b75244215005/src/hsluv.c#L44

I guess the Haxe version got the precision wrong, and caused all generated code (Python, etc.) not precise enough? Does the numbers in the C version right?

**Comment by Smart-Hypercube** [comment]
Python version:

https://github.com/hsluv/hsluv-python/blob/dd04822de2ae4ddacd31e427c2ab894e833275fb/hsluv.py#L14

It's not precise enough.

**Comment by mity** [comment]
> Does the numbers in the C version right?

(As I am only author of the C implementation, I cannot provide any info about any other implementation.)

The C version originally took the numbers from the ObjC implementation it was based on. But I later re-computed the formulas in https://github.com/hsluv/hsluv/blob/master/math/cie.mac for higher precision (manually at some math website, for the lack of better tools on my computer; I don't know how to work with the `.mac` files directly). 

I did that because because, as far as I can remember, the original implementation was strangely mixing `float` and `double` internally. In the C version, I have eventually switched to `double`-only because my testing showed the `float` accuracy was relatively bad.

Given the C version provides the testing tool, I am very confident it now has [much better accuracy](https://github.com/hsluv/hsluv-c/commit/4b2f18674268147bdf1e236c06d38f611e0cf7e0#diff-076fcca93414d3e2b632f524b29051f3L7) than with the original constants.

Feel free also to re-compute the formulas independently to verify correctness of the numbers.

**Comment by Smart-Hypercube** [comment]
Good job, mity! I verified those numbers in the C version against https://github.com/colour-science/colour , which computes everything from scratch using numpy, and the numbers matches.

By the way, I want to point out that you do not need to keep so many digits -- you can keep only 17 significant digits, which will result in exactly the same `double` values. For example:
```
[
    [3.2409699419045213, -1.5373831775700935, -.49861076029300328],
    [-.96924363628087983, 1.8759675015077207, .041555057407175612],
    [.055630079696993608, -.20397695888897656, 1.0569715142428786],
]
```

I just used these numbers to write my own functions for CIELUV and sRGB converting. Never thought it would be this hard to find the correct numbers online -- lots of codes are using not precise enough numbers or even wrong numbers (slightly off due to computed from numbers not precise enough). Thank you for your quality codes!

**Comment by mity** [comment]
> you can keep only 17 significant digits, which will result in exactly the same double values.

On most platforms, yes.

But I think the C standard does not specify the precision that way and that depending on a platform and compiler, the precision may be theoretically higher and maybe even lower. It only says when the type precision is lower then what the literal provides, it replaces the number literal with the closest number which can be represented by the type. That's why I kept all the precision I've got from the tool (it allowed configuring for number of decimal digits and not valid digits but whatever).
